new: pivot tables
ClickNToulon/clickntoulon-laravel pull request #11
Opened 2022-11-03 14:09 UTC by corentinthibaud

Adding pivot tables for relationships set up in cla-12

2022-11-03 17:22 UTC, qbtl commented on database/migrations/2022_10_22_205136_create_product_shop_pivot_table.php
> +            $table->primary(['product_id', 'shop_id']);
I don't understand what you are doing, could you explain it to me ?

2022-11-03 20:46 UTC, corentinthibaud commented on database/migrations/2022_10_22_205136_create_product_shop_pivot_table.php
> +            $table->primary(['product_id', 'shop_id']);
In Laravel, to make a Many-to-Many relationship, you need a pivot table. This one is just mapping each product to its shop (although as I am writing this, it should be a Many-to-One relationship)

2022-11-03 20:52 UTC, qbtl commented on database/migrations/2022_10_22_205136_create_product_shop_pivot_table.php
> +            $table->primary(['product_id', 'shop_id']);
Ok but why do you add a big int column and a foreign column when you could add a foreignId column that does just that but simpler ?
It does simplifies the code, makes it easier to maintain later.

2022-11-03 20:54 UTC, corentinthibaud commented on database/migrations/2022_10_22_205136_create_product_shop_pivot_table.php
> +            $table->primary(['product_id', 'shop_id']);
Because I like to make non-sense, didn't you know ? lol

2022-11-03 22:14 UTC, qbtl requested changes
You need to change the big int and foreign columns to a single foreignId column in all files

2022-11-03 22:14 UTC, qbtl commented on database/migrations/2022_10_22_205224_create_shop_tag_pivot_table.php
> +            $table->primary(['shop_id', 'tag_id']);
Same problem as the precedent review. Change both big int and foreign columns to a single foreignId column

2022-11-06 13:45 UTC, qbtl requested changes
You can remove the product_product_price_pivot migration as it already exists

2022-11-07 15:03 UTC, qbtl approved these changes
LGTM ! 👍

2022-11-07 15:03 UTC, merged